version: '3.8'
services:
  zookeeper:
    image:  'bitnami/zookeeper:latest'
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_SESSION_TIMEOUT_MS=60000
    ports:
      - "9092:9092"
  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - "6379:6379"
